### ISSUE TITLE
start, finish

### ISSUE THREAD

**Issue by hjun555** [swsnu/swpp17-team10#24]
start 버튼 누르자마자 포인트 차감되는 걸로 지금 되는데 이게 클라이언트 안심을 위해서라도

도착지 근처에서 따로 finish버튼 누를 수 있게 해야 안전상에 문제가 조금 해결될 거 같은데

현재 위치랑 도착지 위치 GPS 오차 범위 내에서 finish 누르게 하자.
이게  그리고 왜 필요하냐면 그래야 방장이 자기한테 조금 더 편한 위치; 예를 들어서 도착지는 행정관이라고 했는데 사실 사람들 많이 끌려서 인기 도착지로 설정한거고 자기는 500동 쪽 갈꺼면 행정관 까지 안가고 그냥 500동 쪽에서 세우겠지. ; 에서 안내리고 약속된 그 장소에서 정확히 내리게하는 효과도 있을 듯!

**Comment by scintilla269** [comment]
택시 타고 출발할 때 어디까지 간다고 말해놓고 중간에 목적지를 바꿀 수 있나요? 그럴 수 있다고 해도 저는 나머지 사람들이 가만있지 않을 것 같아요. 그리고 GPS는 활용하기가 좀 어려운 게 GPS가 위치를 제대로 못 잡을 수도 있고(오차가 문제가 아니라 아예 못 잡는 경우), 조작도 가능해서요.

**Comment by scintilla269** [comment]
별다른 의견이 없으면 닫아주세요.
